name: Deploy Azure Function

on:
  push:
    branches:
      - "main"
    paths:
      - "src/functions/**"
      - ".github/workflows/function.yml"
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  AZURE_FUNCTION_PACKAGE_PATH: 'src/functions'  

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}      


    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTION_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: Azure Login
      uses: Azure/login@v1.1
      with:          
        creds: ${{ secrets.AZURE_CREDENTIALS }}          
        enable-AzPSSession: false  

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTION_PACKAGE_PATH }}/output'              

    - name: Deploy Event Grid Subs      
      uses: Azure/arm-deploy@v1.0.1
      with:        
        scope: resourcegroup          
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        region: ${{ env.LOCATION }}        
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_MEDIA_SPOKE_NAME }}        
        template: bicep/event.bicep   
        parameters: location=${{ env.LOCATION }} functionId=${{ secrets.AZURE_FUNCTION_ID }} storageId=${{ secrets.AZURE_STORAGE_MEDIA_ID }} storageName=${{ secrets.AZURE_STORAGE_MEDIA_NAME }}
        deploymentMode: Incremental                